In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import (AutoMinorLocator, MultipleLocator)
wl = 555 * 10**(-9)

In [25]:
def d(a,b, m = 1):
    return m*wl/(np.sin(np.arctan(a/b)))

In [26]:
a = np.array([175, 185, 162])
b = np.array([235, 247, 215])
d1 = d(a,b)
print(np.rad2deg(np.arctan(a/b)))
print(d1)
print(f"{np.mean(d1)*10**9}+-{np.std(d1)*10**9} нм")

[36.67434967 36.83276494 36.99759977]
[9.29233983e-07 9.25800194e-07 9.22261550e-07]
925.765242609262+-2.8465913118766784 нм


In [27]:
a = np.array([6, 7, 7.5])
b = np.array([1390, 1385, 1385])
dgor = d(a,b)
print(dgor)
print(f"{np.mean(dgor)*10**6}+-{np.std(dgor)*10**6} мкм")

[0.00012858 0.00010981 0.00010249]
113.62660577884854+-10.98531063850313 мкм


In [28]:
a = np.array([71, 65, 70])
b = np.array([1400, 1300, 1400])
d2 = d(a,b)
print(d2)
print(f"{np.mean(d2)*10**6}+-{np.std(d2)*10**6} мкм")

[1.09577261e-05 1.11138663e-05 1.11138663e-05]
11.061819608923027+-0.07360519147839704 мкм


In [38]:
r1 = np.array([30, 33])
r2 = np.array([55, 62])
r3 = np.array([80, 85])
b = np.array([1200, 1320])
d3 = np.append(d(r1, b), [d(r2, b, 2), d(r3, b, 3)])
print(d3*10**6)
print(f"{np.mean(d3)*10**6}+-{np.std(d3)*10**6} мкм")

[22.20693642 22.20693642 24.24360597 23.65831188 25.03043847 25.91002309]
23.87604204094291+-1.3677260228470594 мкм


In [47]:
teta = (7-5)/(3650-1100)
print(np.rad2deg(teta))
print(np.rad2deg(1.2*wl/(0.0045)))

0.04493786628477045
0.008479775367936185


In [50]:
l = 0.265
I0 = 4.2
Iopt = 1.6
Dp = 10*np.log10(I0/Iopt)
print(Dp)
print(Dp/l)

4.191293077419757
15.816200292150025
